# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: MuleSoft-CD

steps:

- script: |
    echo "====== FULL POM.XML ======"
    cat /home/vsts/work/1/s/pom.xml
    echo "====== cloudHub2 CHECK ======"
    grep -n "cloudHub2" /home/vsts/work/1/s/pom.xml || echo "❌ cloudHub2Deployment NOT FOUND in pom.xml"
  displayName: 'Print pom.xml'

- task: Maven@3
  displayName: 'Build and Deploy to CloudHub 2.0'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package mule:deploy'
    publishJUnitResults: false
    options: >-
      -DskipTests
      -Danypoint.clientId=$(ANYPOINT_CLIENT_ID)
      -Danypoint.clientSecret=$(ANYPOINT_CLIENT_SECRET)
      -Danypoint.orgId=$(ANYPOINT_ORG_ID)